// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbeayrhdytwshoipnmwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZWF5cmhkeXR3c2hvaXBubXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTk4ODEsImV4cCI6MjA1ODkzNTg4MX0.U2NFgrUg_yIRgbkjImE1PiJAa4XIwV5Nwk9W5_qy_4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);